### ISSUE TITLE
[Bug] With one Notification you have to tap twice to open it

### ISSUE THREAD

**Issue by Hack4Life** [Ominousness/StackXI#12]
This tweak works great (thanks for you work!) if you get more than one notification from an App. But if you get only one notification from an app you have to tap this notification twice to open it. 

Would be great if you can have a look at it :) 

Greetings from Austria,
Fabian

**Comment by Hack4Life** [comment]
Looks through the commits - looks like it should be already fixed ([according to this commit](https://github.com/Ominousness/StackXI/commit/beb2ebf79ecd80f53c32209431ea37fcfcd5d2bf)) but it still does not work

**Comment by Nayuta-Kani** [comment]
It's fixed, but the build isn't live yet. You'll have to compile from the source if you want the fix now, or wait for Ominousness to release a new build.

**Comment by pixelomer** [comment]
I have the same issue, I will try building master.

**Comment by Nayuta-Kani** [comment]
If you need, Ive compiled my own branch with this fix and a little tweak to it (configurable in settings) if anyone else also needs: https://www6.zippyshare.com/v/QfyYhfKT/file.html

**Comment by pixelomer** [comment]
I compiled it myself and the bug doesn't seem to occur anymore.

**Comment by Ominousness** [comment]
Fixed.
