### ISSUE TITLE
[Bug/Request] Weird order of notifications/ stacks

### ISSUE THREAD

**Issue by D3m3rion** [Ominousness/StackXI#4]
Stacks seem to always be at the top and single notifications mostly at the bottom.
If I get a new notification onto a stack, it just stays in place.
Would it be possible to treat normal notifications the same way as stacks, and simply put the latest stack/notification on the first place/at the top of the list?

For example: I get a WhatsApp notification at 1 pm, and a Twitter notification at 2 pm and at 3 pm.
The twitter stack is now on the top and the WhatsApp one on the bottom. If I now get a new WhatsApp notification at 4 pm, the WhatsApp stack stays at the bottom and does not go over the Twitter stack.
A single notification from Facebook will always stay on the lowest place.
Or is this related to the notification history? That one doesn't seem to work correctly.

If I manage to get a screenshot, I'll add it. EDIT: See screenshots below.

![img_0537](https://user-images.githubusercontent.com/26471657/44632970-76e07980-a984-11e8-9413-ae6f70204d47.jpg)

**Comment by Ominousness** [comment]
Fixed in 0.4.0.
